config/routes.rb
Rails.application.routes.draw do

  root 'home#rankingslanding'
  get '/home' => 'home#index'
  get '/admin' => 'puppies#index'
  get '/admin/puppiesall' => 'puppies#puppiesall'
  get 'puppy/add' => 'puppies#add'
  get '/draft' => 'home#draft'
  get '/created' => 'home#created'
  get '/vote' => 'home#vote'
  post '/dovote' => 'home#dovote'
  get '/voted' => 'home#voted'
  get '/edit' => 'home#edit'
  get '/selfclose' => 'home#selfclose'
  get '/finalstats' => 'home#finalstats'
  post '/createteam' => 'home#createteam'
  post '/editteam' => 'home#editteam'
  get '/rankings' => 'home#rankings'

  resources :users, only: :index
  scope '/admin' do
  resources :teams
  resources :puppies
  resources :settings
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations",
                                       :sessions => "sessions" }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :json
  before_filter :set_access_control_headers 
  before_filter :redirect, except: [:rankings, :finalstats] 
  before_action :authenticate_user!, except: [:index, :rankingslanding]
  layout :choose_layout
 
 def choose_layout
     case action_name
    when "rankingslanding" 
      "application_rankingslanding"  
    else
      "application"
 end
end

    
  
 def redirect
    if current_user != nil 
      sql = "SELECT begin_date, end_date FROM `settings`"
    @settings  = ActiveRecord::Base.connection.execute(sql);
    beginend = @settings.first

    if beginend
      session['begin_datetime'] = beginend[0].to_s
      session['end_datetime'] =  beginend[1].to_s
   
      time =  Time.now
      time = time.in_time_zone("Eastern Time (US & Canada)")
      timebegin = Time.parse(session['begin_datetime']) + 5.hours
      timebegin = timebegin.in_time_zone("Eastern Time (US & Canada)")
      timeend = Time.parse(session['end_datetime']) + 5.hours
      timeend =  timeend.in_time_zone("Eastern Time (US & Canada)")
       
      if time >= timebegin
        #duriing or after the game - nothing
        if time <= timeend
         #during the game - go to rankings
           puts 'during the game'
           session['status'] = 'during'
           redirect_to action: 'rankings' 
         return
        else
         #after the game - go to  finalstats
         puts 'after the game'
         session['status'] = 'after'
         redirect_to action: 'finalstats' 
         return
        end
      else
        # before the game - nothing happens
        session['status'] = 'before or undefined dates'
        puts 'before the game'
        # return
      end
    end
    end
 end

  def index
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read) 
    response.headers['P3P'] = 'CP="NON DSP COR CURa IVAa IVDa CONa OUR NOR STA"'
     if current_user != nil 
      team = usersteam
   if team  != nil
      @puppies = Puppy.all

      render :template => "home/edit", :locals => { :pup1 => team[1] || -1 , :pup2 => team[2] || -1 , :pup3 => team[3] || -1, :puppies=>@puppies, :votestats=>votestats } 
   else
      redirect_to action: 'draft'
   end
   else 
    @puppies = Puppy.all
    respond_with(@puppies) 
   end 
  end
  

  def noteams
     sql = "SELECT count(*) as cnt FROM `teams`" 
   @res = ActiveRecord::Base.connection.execute(sql);
   team = @res.first  
   return team[0]
  end

  def votestats
       sqlruff  = "SELECT count(*) AS ruff FROM `users` WHERE vote ='R' " 
   sqlfluff = "SELECT count(*) AS fluff FROM `users` WHERE vote ='F' " 

   @resruff  = ActiveRecord::Base.connection.execute(sqlruff);
   @resfluff = ActiveRecord::Base.connection.execute(sqlfluff);
   
   ruff = @resruff.first
   fluff = @resfluff.first

   sum = ruff[0].to_i + fluff[0].to_i
   pctfluff = fluff[0].to_f *  100 / sum 
   pctruff =  ruff[0].to_f *  100 / sum 
   
   votestats = Array.new
   votestats[0] = pctfluff
   votestats[1]  = pctruff
   return votestats
  end


  def usersteam
    sql = "SELECT id, pup1,pup2,pup3 FROM `teams` WHERE user_id = " + current_user.id.to_s
   @res = ActiveRecord::Base.connection.execute(sql);
   team = @res.first 
   if team != nil
   team[1] = team[1] || -1
   team[2] = team[2] || -1
   team[3] = team[3] || -1
   end
   return team
  end

  def ranking 
           ranking = 0
            touchdown = 7
            fieldg = 3
            tackle = 2
            takeaway = 3
            penalty = -2
    
   @allpuppies = Puppy.all
   @allteams = Team.all
   team = usersteam
   rs = Array.new
   results = Array.new
   teamscores = Array.new        
   if usersteam != nil
   @allpuppies.each_with_index do |puppy, index| 
   res = ( touchdown * puppy.score_touchdowns) + (fieldg *  puppy.score_field_goals) + (tackle * puppy.score_tackles) + (takeaway * puppy.score_takeaways) + (penalty * puppy.score_penalties) 
   # puts "puppy" + puppy.id.to_s + " has " + res.to_s
   results[puppy.id] = res  
   end 
   sql = "SELECT * FROM `puppies` WHERE id in (" + team[1].to_s + "," + team[2].to_s + ", " + team[3].to_s + ")" 
   @puppies = ActiveRecord::Base.connection.execute(sql); 
   score = 0
      @puppies.each_with_index do |puppy, index|
    score += ( touchdown * puppy[6]) + (fieldg *  puppy[15]) + (tackle * puppy[9]) + (takeaway * puppy[8]) + (penalty * puppy[7]) 
   # puts " team score: "+score.to_s 
    end 

   @allteams.each do |team| 
   # puts team.id
     if team
     p1i = team.pup1 || -1
     p2i = team.pup2 || -1
     p3i = team.pup3 || -1

      p1 = results[p1i] || 0
      p2 = results[p2i] || 0
      p3 = results[p3i] || 0
      teamscore = p1 + p2  + p3
   #   puts "team x has: "+teamscore.to_s
      teamscores.push( teamscore);
     end
   end
  teamscores.sort! {|x, y| x <=> y}
 # puts teamscores
  noteams = teamscores.count
  ranking =0
  teamscores.each_with_index do |tscore, index| 
    if score < tscore then   
     # puts 'index >>>' + index.to_s + '  score' + score.to_s + ' tscore ' + tscore.to_s
     ranking = noteams - index
     break
    end
  end

   if score == 0
      ranking = teamscores.count
    end

  rs[0] = ranking
  rs[1] = score
  else
  rs[0] = 0
  rs[1] = 0
  end
  return rs
  end



  def finalstats
   if current_user != nil
   votes = votestats
   rank = ranking
   get_friends_image_who_drafted
   render :template => "home/finalstats", :locals => {:ranking => rank[0], :votes => votes, :noteams => noteams, :score=>rank[1], :puppies=>@puppies } 
   else
      redirect_to action: 'index'
   end 
   end


  def draft  
  if current_user != nil
       team = usersteam
    if team  != nil
      session['tid'] = team[0]
      @puppies = Puppy.all
      render :template => "home/draft", :locals => { :pup1 => team[1] || -1, :pup2 => team[2] || -1 , :pup3 => team[3] || -1 , :puppies=>@puppies } 
   else
      # session['tid'] = team[0]
      @puppies = Puppy.all
      render :template => "home/draft", :locals => { :pup1=>'***', :pup2=>'***', :pup3=>'***', :puppies=>@puppies }       
   #   redirect_to action: 'draft'
   end
   else
      redirect_to action: 'index'
   end 
  end


  def dovote  
   if  @user = User.find(current_user.id)   
   # User.where('user_id = ?', current_user.id.to_s).update_all(user_params)    
     sql = "UPDATE users SET vote='" + user_params['vote'] + "' WHERE id=" + current_user.id.to_s
      @res  = ActiveRecord::Base.connection.execute(sql);
   # @user.update() 
     render :status=>200, :json=>{:id=>@user.id, :message=>'success'}       
   else
     render :status=>200, :json=>{ :message=>'error'}       
     
   end      
  
  end

   def editteam  
     
      team = usersteam
   if team  != nil
      session['tid'] = team[0]
      
      Team.where('user_id = ?', current_user.id.to_s).update_all(team_update_params)      
            render :status=>200, :json=>{:id=>team[0]}
            return  
          
      else 
          @team = Team.new(team_update_params)
          if  @team.save
          render :status=>200, :json=>{:id=>@team.id}       
           session['tid'] = @team.id
             return
          end 

      end     
  end

  def vote  
  end
   def selfclose  
  end

  def voted  
   sqlruff  = "SELECT count(*) AS ruff FROM `users` WHERE vote ='R' " 
   sqlfluff = "SELECT count(*) AS fluff FROM `users` WHERE vote ='F' " 

   @resruff  = ActiveRecord::Base.connection.execute(sqlruff);
   @resfluff = ActiveRecord::Base.connection.execute(sqlfluff);
   
   ruff = @resruff.first
   fluff = @resfluff.first

   sum = ruff[0].to_i + fluff[0].to_i
   pctfluff = fluff[0].to_f *  100 / sum 
   pctruff =  ruff[0].to_f *  100 / sum 
   puts pctfluff
   puts pctruff
   render :template => "home/voted", :locals => { :pctfluff => pctfluff, :pctruff => pctruff, :tid=>session['tid'] } 

  end
  

   def edit  
   if current_user != nil
      team = usersteam 
      vote = votestats
   if team  != nil
      session['tid'] = team[0]
      @puppies = Puppy.all
      render :template => "home/edit", :locals => { :pup1 => team[1] || -1, :pup2 => team[2] || -1, :pup3 => team[3] || -1, :puppies=>@puppies, :votestats=>vote} 
   else
      @puppies = Puppy.all
      render :template => "home/edit", :locals => { :pup1=>'***', :pup2=>'***', :pup3=>'***', :puppies=>@puppies, :votestats=>vote } 
      
   #   redirect_to action: 'draft'
   end

   else 
     redirect_to action: 'index'
   end 

   end

 #  def edited    
 #  sql = "SELECT pup1,pup2,pup3 FROM `teams` WHERE id = " + session['tid'].to_s
 #  @res = ActiveRecord::Base.connection.execute(sql);
 #  team = @res.first          
 #  sql = "SELECT * FROM `puppies` WHERE id in (" + team[0].to_s + "," + team[1].to_s  + "," + team[2].to_s   + ")" 
 #  @puppies = ActiveRecord::Base.connection.execute(sql); 
 #  respond_with(@puppies)         
 # end

   def created    

   team = usersteam        	
   if team
    get_friends_image_who_drafted
    sql = "SELECT * FROM `puppies` WHERE id in (" + team[1].to_s  + "," + team[2].to_s  + "," + team[3].to_s  + ")" 
    @puppies =  ActiveRecord::Base.connection.execute(sql);   
     fpup = @puppies.first

    if  current_user.vote == nil
     redirect_to action: 'vote'
    else
    render :template => "home/created", :locals => { :pup1=>fpup, :pup2=>'***', :pup3=>'***', :puppies=>@puppies } 
    end
   
   else
    flash[:error] = "Team not found"
    redirect_to root_path
   end
  end

   def createteam  
   team = usersteam
   if team  != nil
          Team.where('user_id = ?', current_user.id.to_s).update_all(team_update_params)      
            render :status=>200, :json=>{:id=>team[0], :action=>'update'}
   else
    @team = Team.new(team_params)
  if  @team.save
     render :status=>200, :json=>{:id=>@team.id, :name=>@team.TEAM_NAME,  :action=>'create'}       
     session['tid'] = @team.id
        return

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <p class="welcome text-center">ALL THE PUPS</p>
      <p class="welcome text-center">You need 3 pups for your team.</p>
      <p class="welcome text-center"><%= current_user.name ? current_user.name : current_user.first_name %>, team</p>
      <div class="col-md-8 col-centered">
        <div class="row">
          <div class="col-xs-2 col-md-4">
            <div class="blue-bg">
              <%= image_tag "pets/empty_dog.png", class: "img-responsive" %>
            </div>
          </div>
          <div class="col-xs-2 col-md-4">
            <div class="blue-bg">
              <%= image_tag "pets/empty_dog.png", class: "img-responsive" %>
            </div>
          </div>
          <div class="col-xs-2 col-md-4">
            <div class="blue-bg">
              <%= image_tag "pets/empty_dog.png", class: "img-responsive" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <select class="image-picker show-html" data-limit="3" multiple="multiple">
      <% @puppies.each_with_index do |puppy, index| %>
        <option data-img-src="assets/<%= puppy.pic %>" data-img-label="<%= puppy.name %>" value="<%= index %>"></option>
      <% end %>
    </select>
  </div>
<% end %>
<%= render "shared/sign_in_modal" %>
<%= render "shared/sign_up_modal" %>

app/views/home/rankings.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="col-md-12 col-sm-12 col-xs-12 col-centered">
      <div class="text-center">
        <p class="created-text">player ranking</p>
        <!-- <p class="team-score">your team score</p> -->
        <hr style="display:inline-block; width:22px; margin-right:8px;" class="small-rule-pacifico">
        <div  class="team-score" style="display:inline-block; height:100%; vertical-align:middle;">
          YOUR TEAM SCORE   <span class="created-text"><%= score %></span>
        </div>
        <hr style="display:inline-block; width:22px; margin-left:8px;" class="small-rule-pacifico">
        <div style="width:100%">
          <div class="col-md-5 col-sm-5 col-xs-5 nopadding">
            <p class="you-ranked" align="right">You ranked <%= ranking %> out of <%= noteams %> teams</p>
          </div>
          <div class="col-md-7 col-sm-7 col-xs-7" style="margin-bottom:7px" align="left">
            <%= link_to '<button type="button" class="btn team-stats" style="display:inline-block">your team stats</button>'.html_safe, finalstats_path %>
             <a href="#" data-toggle="modal" data-target="#myModal" class="btn signout" style="display:inline-block">POLL RESULTS</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-10 col-sm-12 col-xs-12 col-centered">
    <div class="" id="ranking">
      <table class="table">
        <thead>
          <tr class="ranking-title">
            <!-- <th class="pups-title">pups</th> -->
            <th></th>
            <th></th>
            <th>team</th>
            <th>touchdowns</th>
            <th>field goals</th>
            <th>takeaways</th>
            <th>tackles</th>
            <th>penalties</th>
            <th></th>
            <!-- <th class="pups-title pull-right">totals</th> -->
          </tr>
          <tr id="ranking-score">
            <th class="pups-title pull-left">pups</th>
            <!-- <th></th> -->
            <th></th>
            <th></th>
            <th class="ranking-score" style="padding-bottom:6px;">7pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">3pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">3pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">2pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">-2pts</th>
            <!-- <th></th> -->
            <th class="pups-title pull-right">totals</th>
          </tr>
          <tr style="height:10px;">
          </tr>
        </thead>
        <tbody>
          <% @puppies.each_with_index do |puppy, index| %>
            <tr class=<%= index == 0 ? "first-tr" : "rest-tr" %>>
              <td class="puppy-thumb"><%= image_tag puppy.pic, class: "pull-left", size: "50x50" %></td>
              <td class="ranking-text pull-left puppy-name"><p><%= puppy.name %></p></td>
              <td><p><%= image_tag puppy.team_name == 'Ruff' ? "ruff_team.png" : "fluff_team.png", class: "img-responsive center-block" %></p></td>
              <td><p><%= puppy.score_touchdowns * 7 %></p></td>
              <td><p><%= puppy.score_field_goals * 3 %></p></td>
              <td><p><%= puppy.score_takeaways * 3 %></p></td>
              <td><p><%= puppy.score_tackles * 2 %></p></td>
              <td><p><%= puppy.score_penalties * -2 %></p></td>
              <td><p><%= puppy.totals %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

 <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content modalbg" align="center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body" style ="max-width:500px;min-height:350px;">       
               <!---  BEGIN STATS    -->
                <div  style="margin-top:14px; padding-left:0px; position:absolute; left:0px;top:20px;">
                          <div class="col-md-12 created-text" align="center">poll results</div>
          <div class="col-md-12 thank-text" style="margin-bottom:25px" align="center">The current vote on whch team will win.</div>

   <div class="col-md-12 col-sm-12 " style="margin-top:14px; padding-left:0px"> 
   <!-- <div class="col-md-1"> </div> -->
   <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12 "> 
  <div class="col-md-8 col-sm-8 col-xs-8 " align="center" style="padding-left:9px;"> 
   <% if votes[1].to_i > votes[0].to_i %>
    <%= image_tag "current_favorite.png", style: "padding-left:0px;" %>
   <% else %>
   <img src="/assets/spacer.png" style="height:21px; width:178px" />
   <% end %> 
   </div> 
     <div class="col-md-12  col-sm-12 col-xs-12">
       <div class="row">
         <div class="col-md-8  col-sm-8  col-xs-8" align="center" style="border-right:3px solid #FAE53E; padding-left:0px; padding-right:0px; padding-bottom-0px;" id="team_ruff" align="center">
          <%= image_tag "ruff_big.png", style: "padding-left:0px; width:150px;" %>
          </div>
         <div class="col-md-3 col-sm-3 col-xs-3 nopadding" style="display: table-cell; vertical-align:top;" align="center">
         <span class="pct" style="position:absolute; top:-8px; left:6px;"> <%= votes[1].to_i %>% </span>
         </div>
        </div>
      </div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-12"> 
         <div class="col-md-8 col-sm-8 col-xs-8" align="center"> 
      <% if  votes[0].to_i > votes[1].to_i %>
    <%= image_tag "current_favorite.png", class: "left-block",  style: "padding-left:0px;" %>
    <% else %>
   <img src="/assets/spacer.png" style="height:21px; width:178px" />
   <% end %> 
   </div>
      <div class="col-md-12  col-sm-12 col-xs-12 "> 
        <div class="row">
          <div class="col-md-8  col-sm-8 col-xs-8" style="border-right:3px solid #FAE53E; padding-left:8px; padding-right:0px; padding-bottom-0px;" id="team_fluff" align="center">
              <%= image_tag "fluff_big.png", class: "img-responsive left-block", style: "padding-left:0px; width:150px;" %>
          </div>
          <div class="col-md-3  col-sm-3 col-xs-3  pct nopadding" align="center">
         <span class="pct" style="position:absolute; top:-8px; left:6px;"> <%= votes[0].to_i  %>% </span>
            </div>
         </div>
      </div>
      </div>
  </div>
   <!-- <div class="col-md-1"></div> -->
   </div>
  </div>
   <!--- END STATS -->

          </div>
        </div>
    </div>
  </div>
  

app/views/home/rankingslandng.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="col-md-12 col-sm-12 col-xs-12 col-centered">
      <div class="text-center">
        <p class="created-text">player ranking</p>
        <!-- <p class="team-score">your team score</p> -->
        <hr style="display:inline-block; width:22px; margin-right:8px;" class="small-rule-pacifico">
        <div  class="team-score" style="display:inline-block; height:100%; vertical-align:middle;">
        LOG IN TO SEE  YOUR TEAM SCORE            </div>
        <hr style="display:inline-block; width:22px; margin-left:8px;" class="small-rule-pacifico">
        <div style="width:100%">
          <div class="col-md-5 col-sm-5 col-xs-5 nopadding">
            <p class="you-ranked" align="right"> <%= noteams %> teams were created</p>
          </div>
          <div class="col-md-7 col-sm-7 col-xs-7" style="margin-bottom:7px" align="left">
            <%= link_to '<button type="button" class="btn team-stats" style="display:inline-block">your team stats</button>'.html_safe, finalstats_path %>
             <a href="#" data-toggle="modal" data-target="#myModal" class="btn signout" style="display:inline-block">POLL RESULTS</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-10 col-sm-12 col-xs-12 col-centered">
    <div class="" id="ranking">
      <table class="table">
        <thead>
          <tr class="ranking-title">
            <!-- <th class="pups-title">pups</th> -->
            <th></th>
            <th></th>
            <th>team</th>
            <th>touchdowns</th>
            <th>field goals</th>
            <th>takeaways</th>
            <th>tackles</th>
            <th>penalties</th>
            <th></th>
            <!-- <th class="pups-title pull-right">totals</th> -->
          </tr>
          <tr id="ranking-score">
            <th class="pups-title pull-left">pups</th>
            <!-- <th></th> -->
            <th></th>
            <th></th>
            <th class="ranking-score" style="padding-bottom:6px;">7pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">3pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">3pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">2pts</th>
            <th class="ranking-score" style="padding-bottom:6px;">-2pts</th>
            <!-- <th></th> -->
            <th class="pups-title pull-right">totals</th>
          </tr>
          <tr style="height:10px;">
          </tr>
        </thead>
        <tbody>
          <% @puppies.each_with_index do |puppy, index| %>
            <tr class=<%= index == 0 ? "first-tr" : "rest-tr" %>>
              <td class="puppy-thumb"><%= image_tag puppy.pic, class: "pull-left", size: "50x50" %></td>
              <td class="ranking-text pull-left puppy-name"><p><%= puppy.name %></p></td>
              <td><p><%= image_tag puppy.team_name == 'Ruff' ? "ruff_team.png" : "fluff_team.png", class: "img-responsive center-block" %></p></td>
              <td><p><%= puppy.score_touchdowns * 7 %></p></td>
              <td><p><%= puppy.score_field_goals * 3 %></p></td>
              <td><p><%= puppy.score_takeaways * 3 %></p></td>
              <td><p><%= puppy.score_tackles * 2 %></p></td>
              <td><p><%= puppy.score_penalties * -2 %></p></td>
              <td><p><%= puppy.totals %></p></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

 <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content modalbg" align="center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </div>
        <div class="modal-body" style ="max-width:500px;min-height:350px;">       
               <!---  BEGIN STATS    -->
                <div  style="margin-top:14px; padding-left:0px; position:absolute; left:0px;top:20px;">
                          <div class="col-md-12 created-text" align="center">poll results</div>
          <div class="col-md-12 thank-text" style="margin-bottom:25px" align="center">The current vote on whch team will win.</div>

   <div class="col-md-12 col-sm-12 " style="margin-top:14px; padding-left:0px"> 
   <!-- <div class="col-md-1"> </div> -->
   <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12 "> 
  <div class="col-md-8 col-sm-8 col-xs-8 " align="center" style="padding-left:9px;"> 
   <% if votes[1].to_i > votes[0].to_i %>
    <%= image_tag "current_favorite.png", style: "padding-left:0px;" %>
   <% else %>
   <img src="/assets/spacer.png" style="height:21px; width:178px" />
   <% end %> 
   </div> 
     <div class="col-md-12  col-sm-12 col-xs-12">
       <div class="row">
         <div class="col-md-8  col-sm-8  col-xs-8" align="center" style="border-right:3px solid #FAE53E; padding-left:0px; padding-right:0px; padding-bottom-0px;" id="team_ruff" align="center">
          <%= image_tag "ruff_big.png", style: "padding-left:0px; width:150px;" %>
          </div>
         <div class="col-md-3 col-sm-3 col-xs-3 nopadding" style="display: table-cell; vertical-align:top;" align="center">
         <span class="pct" style="position:absolute; top:-8px; left:6px;"> <%= votes[1].to_i %>% </span>
         </div>
        </div>
      </div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-12"> 
         <div class="col-md-8 col-sm-8 col-xs-8" align="center"> 
      <% if  votes[0].to_i > votes[1].to_i %>
    <%= image_tag "current_favorite.png", class: "left-block",  style: "padding-left:0px;" %>
    <% else %>
   <img src="/assets/spacer.png" style="height:21px; width:178px" />
   <% end %> 
   </div>
      <div class="col-md-12  col-sm-12 col-xs-12 "> 
        <div class="row">
          <div class="col-md-8  col-sm-8 col-xs-8" style="border-right:3px solid #FAE53E; padding-left:8px; padding-right:0px; padding-bottom-0px;" id="team_fluff" align="center">
              <%= image_tag "fluff_big.png", class: "img-responsive left-block", style: "padding-left:0px; width:150px;" %>
          </div>
          <div class="col-md-3  col-sm-3 col-xs-3  pct nopadding" align="center">
         <span class="pct" style="position:absolute; top:-8px; left:6px;"> <%= votes[0].to_i  %>% </span>
            </div>
         </div>
      </div>
      </div>
  </div>
   <!-- <div class="col-md-1"></div> -->
   </div>
  </div>
   <!--- END STATS -->

          </div>
        </div>
    </div>
  </div>
  

app/views/home/selfclose.html.erb
<script type="text/javascript">self.close();</script>