config/routes.rb
Rails.application.routes.draw do

  root 'home#rankingslanding'
  get '/home' => 'home#index'
  get '/admin' => 'puppies#index'
  get '/admin/puppiesall' => 'puppies#puppiesall'
  get 'puppy/add' => 'puppies#add'
  get '/draft' => 'home#draft'
  get '/created' => 'home#created'
  get '/vote' => 'home#vote'
  post '/dovote' => 'home#dovote'
  get '/voted' => 'home#voted'
  get '/edit' => 'home#edit'
  get '/selfclose' => 'home#selfclose'
  get '/finalstats' => 'home#finalstats'
  post '/createteam' => 'home#createteam'
  post '/editteam' => 'home#editteam'
  get '/rankings' => 'home#rankings'

  resources :users, only: :index
  scope '/admin' do
  resources :teams
  resources :puppies
  resources :settings
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations",
                                       :sessions => "sessions" }

end

app/models/puppy.rb
# == Schema Information
#
# Table name: puppies
#
#  id               :integer          not null, primary key
#  PUPPY_NAME       :string(255)
#  PUPPY_BREED      :string(255)
#  PUPPY_SEX        :string(255)
#  PUPPY_AGE        :integer
#  PUPPY_FUN_FACT   :string(255)
#  SCORE_TOUCHDOWNS :integer          default(0), not null
#  SCORE_PENALTIES  :integer          default(0), not null
#  SCORE_TAKEAWAYS  :integer          default(0), not null
#  SCORE_TACKLES    :integer          default(0), not null
#  PUPPY_PIC        :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Puppy < ActiveRecord::Base

    has_many :puppy_teams
	has_many :teams, :through => :puppy_teams

  def totals
    (score_touchdowns * 7) + (score_takeaways * 3) + (score_tackles * 2) + (score_field_goals * 3) + (score_penalties * -2)
  end
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  before_filter :set_access_control_headers 
  before_action :set_puppy, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verify_admin
  respond_to :html, :json
  layout 'admin_panel'


def verify_admin
 if current_user.role != 'admin' then
      redirect_to  :controller => "home", :action => "index" 
  end
end

  def puppiesall
      @puppies = Puppy.all
      respond_with(@puppies)
  end

  def index
    @puppies = Puppy.all
    respond_with(@puppies)
  end

  def draft
    @puppies = Puppy.all
    respond_with(@puppies)
  end

  def show
    redirect_to action: "index" 
  end

  def new
     
    @puppy = Puppy.new
    respond_with(@puppy)
      
  end

  def edit

 
  end

  def create
     
    @puppy = Puppy.new(puppy_params)
    @puppy.save
   # respond_with(@puppy)
    redirect_to action: "index" 
    
  end

  def update
 if @puppy.update(puppy_params)

  respond_to do |format|
  format.html  { redirect_to :action => "index" } 
  format.json  { render :status=>200, :json=>{:id=>@puppy.id,
                                              :score_touchdowns=>@puppy.score_touchdowns,
                                              :score_takeaways=>@puppy.score_takeaways,
                                              :score_tackles=>@puppy.score_tackles,
                                              :score_penalties=>@puppy.score_penalties,
                                              :score_field_goals=>@puppy.score_field_goals } }
  end  

 end
  end

  def destroy
     
    @puppy.destroy
    respond_with(@puppy)
       
  end

  def add
  end

  private
    def set_puppy
      @puppy = Puppy.find(params[:id])
    end

    def puppy_params
      params.require(:puppy).permit(:id, :name, :team_name, :breed, :sex, :age, :fun_fact, :score_touchdowns, :score_field_goals, :score_penalties, :score_takeaways, :score_tackles, :pic, :big_pic)
    end

      def set_access_control_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Expose-Headers'] = 'Etag'
      headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD'
      headers['Access-Control-Allow-Headers'] = '*, x-requested-with, Content-Type, If-Modified-Since, If-None-Match'
      end

end

app/views/puppies/_form.html.erb
<%= form_for(@puppy) do |f| %>
  <% if @puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% @puppy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-7">
  <div class="col-md-6 form-group">
    <%= f.label "Name" %><br>
    <%= f.text_field :name,  class: "form-control" %>
  </div>
  <div class="col-md-6 form-group">
    <%= f.label "Breed" %><br>
    <%= f.text_field :breed, class: "form-control"  %>
  </div>
  </div>
  <div class="col-md-7">
  <div class="col-md-6 form-group">
    <%= f.label "Gender" %><br>
   <%= f.select :sex,   [['Male', 'Male'], ['Female', 'Female']]  ,  { } , {  class: 'form-control',  } %>  
  </div>
    <div class="col-md-6 form-group">
    <%= f.label "Belongs to team" %><br>
   <%= f.select :team_name, %w[Select Fluff Ruff] , {}, {  class: 'form-control'} %>  
  </div>
  </div>
   <div class="col-md-7 form-group">
  <div class="col-md-8 form-group">
    <%= f.label "Fun Fact" %><br>
    <%= f.text_area :fun_fact, class: "form-control"  %>
  </div>
    <div class="col-md-4 form-group">
    <%= f.label "Age" %><br>
    <%= f.text_field :age, class: "form-control"  %>
  </div>
  </div>
   <div class="col-md-7">
  <div class="col-md-6 form-group">
    <%= f.label "Touchdowns" %><br>
    <%= f.number_field :score_touchdowns, class: "form-control"  %>
  </div>
  <div class="col-md-6 form-group">
    <%= f.label "Penalties" %><br>
    <%= f.number_field :score_penalties, class: "form-control"  %>
  </div>
   </div>
    <div class="col-md-7">
  <div class="col-md-6 form-group">
    <%= f.label "Tekeaways" %><br>
    <%= f.number_field :score_takeaways, class: "form-control"  %>
  </div>

  <div class="col-md-6 form-group">
    <%= f.label "Tackles" %><br>
    <%= f.number_field :score_tackles, class: "form-control"  %>
  </div>
  </div>
  <div class="col-md-7">
    <div class="col-md-6 form-group">
    <%= f.label "Field Goals" %><br>
    <%= f.number_field :score_field_goals, class: "form-control"  %>
  </div>
   
    <div class="col-md-6 form-group">
     
  </div>
  </div>

   <div class="col-md-7 form-group">
  <div class="col-md-12 form-group">
    <%= f.label :pic %><br>
    <%= f.text_field :pic, class: "form-control"  %>

  </div>
  </div>
     <div class="col-md-7 form-group">
  <div class="col-md-12 form-group">
    <label> Big picture (draft page)</label><br>
    <%= f.text_field :big_pic, class: "form-control"  %>

  </div>
  </div>
  <div class="col-md-7 form-group">
    <%= f.submit "Create / Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/puppies/edit.html.erb
<h2>Edit puppy</h2>

<%= render 'form' %>
<%= link_to 'Back', puppies_path %>

app/views/puppies/index.html.erb
<style type="text/css">
  
  .plusminusdiv { 
   display:inline-block;
   width: 20px;
   height: 20px;
   border-radius: 10px;
   color:white;
   font-weight: 800;
   cursor: pointer;
  }

  .plus {  background-color: #5Cb85C; }
  .minus {  background-color: #D9534F; }
  .score { 
   vertical-align: middle;
   padding-top: 20px;
   padding-bottom: 20px;

   font-family: 'Cubano';
   font-size:20px;   
  }
</style>
<script type="text/javascript">
  
function preview() { 

  window.open("/rankings", "","width=900, height=950,  scrollbars=yes");
}

</script>
<h2 >Dashboard - <a href="javascript:preview()">preview</a></h2>  
<div class="col-md-8">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Name</th>
      <th>Team</th>
      <th>Touchdowns</th>
      <th>Field Goals</th>
      <th>Takeaways</th>
      <th>Tackles</th>
      <th>Penalties</th>
    </tr>
  </thead>

  <tbody>
    <% @puppies.each do |puppy| %>
      <tr>
        <td><%= image_tag puppy.pic %></td>
        <td><%= puppy.name %></td>
        <td><%= puppy.team_name %></td>
      
        <td id="<%= puppy.id %>" class="tdscores" align="center">
        <div id="score_touchdowns_<%= puppy.id %>" class="score pct">   <%= puppy.score_touchdowns %> </div>
         <div class="plusminusdiv minus" onclick="javascript:upd(<%= puppy.id %>, 'score_touchdowns', 'minus')"> - </div> 
         <div class="plusminusdiv plus" onclick="javascript:upd(<%= puppy.id %>, 'score_touchdowns', 'plus')"> + </div> 
        </td>
        <td id="<%= puppy.id %>" class="tdscores" align="center">
        <div id="score_field_goals_<%= puppy.id %>" class="score"><%= puppy.score_field_goals %></div>
         <div class="plusminusdiv minus" onclick="javascript:upd(<%= puppy.id %>, 'score_field_goals', 'minus')"> - </div>  
         <div class="plusminusdiv plus" onclick="javascript:upd(<%= puppy.id %>, 'score_field_goals', 'plus')"> + </div> 
        </td>
        <td id="<%= puppy.id %>" class="tdscores" align="center">
        <div  id="score_takeaways_<%= puppy.id %>" class="score"><%= puppy.score_takeaways %></div>
         <div class="plusminusdiv minus" onclick="javascript:upd(<%= puppy.id %>, 'score_takeaways', 'minus')"> - </div> 
         
         <div class="plusminusdiv plus" onclick="javascript:upd(<%= puppy.id %>, 'score_takeaways', 'plus')"> + </div> 
        </td>
        <td id="<%= puppy.id %>" class="tdscores" align="center">
        <div id="score_tackles_<%= puppy.id %>" class="score"><%= puppy.score_tackles %></div>
         <div class="plusminusdiv minus" onclick="javascript:upd(<%= puppy.id %>, 'score_tackles', 'minus')"> - </div>
         <div class="plusminusdiv plus" onclick="javascript:upd(<%= puppy.id %>, 'score_tackles', 'plus')"> + </div> 

        </td>
        <td id="<%= puppy.id %>" class="tdscores" align="center" >
        <div id="score_penalties_<%= puppy.id %>" class="score">  <%= puppy.score_penalties %> </div>
         <div class="plusminusdiv minus" onclick="javascript:upd(<%= puppy.id %>, 'score_penalties', 'minus')"> - </div> 
         <div class="plusminusdiv plus" onclick="javascript:upd(<%= puppy.id %>, 'score_penalties', 'plus')"> + </div> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puppy', new_puppy_path %>
</div>

<script type="text/javascript">


function upd(id, field, action) {

   var value = $('#' + field + '_' + id).html()
    action == 'plus' ? value++ : value--
   var arr = {}
   var parr = {}
   parr[field] = value
   arr['puppy'] = parr

  var  d = JSON.stringify(arr)
   $.ajax( {
    type :"PUT", 
    async :true, 
    url : '/admin/puppies/'+id+'.json',
    dataType: 'json',
    contentType: "application/json; charset=utf-8",
    data: d ,
    success: function(data) {  
          if (data.id) {
            console.log('updated ok')
            $('#' + field + '_' + id).html(data[field])
            }
          else 
         {   
             console.log('updated not ok')
            }
               },
    error: function(error) {
                console.log('updated not ok')
                }
        });  
 
}



</script>

app/views/puppies/new.html.erb
<h1>New puppy</h1>

<%= render 'form' %>

<%= link_to 'Back', puppies_path %>

app/views/puppies/puppiesall.html.erb
<h2>Puppies</h2>
<div class="col-md-10">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th>Name</th>
      <th>Breed</th>
      <th>Team</th>
      <th>Sex</th>
      <th>Age</th>
      <th>Touchdowns</th>
      <th>Field Goals</th>
      <th>Takeaways</th>
      <th>Tackles</th>
      <th>Penalties</th>
    
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @puppies.each do |puppy| %>
      <tr>
        <td><%= image_tag puppy.pic %></td>
        <td><%= puppy.name %></td>
        <td><%= puppy.breed %></td>
        <td><%= puppy.team_name %></td>
        <td><%= puppy.sex %></td>
        <td><%= puppy.age %></td>
        <td><%= puppy.score_touchdowns %></td>
        <td><%= puppy.score_field_goals %></td>
        <td><%= puppy.score_takeaways %></td>
        <td><%= puppy.score_tackles %></td>
        <td><%= puppy.score_penalties %></td>
        <td><%= link_to 'Edit', edit_puppy_path(puppy) %></td>
        <td><%= link_to 'Delete', puppy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puppy', new_puppy_path %>
</div>

app/views/puppies/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Puppy name:</strong>
  <%= @puppy.name %>
</p>

<p>
  <strong>Puppy breed:</strong>
  <%= @puppy.breed %>
</p>

<p>
  <strong>Puppy sex:</strong>
  <%= @puppy.sex %>
</p>

<p>
  <strong>Puppy age:</strong>
  <%= @puppy.age %>
</p>

<p>
  <strong>Puppy fun fact:</strong>
  <%= @puppy.fun_fact %>
</p>

<p>
  <strong>Score touchdowns:</strong>
  <%= @puppy.score_touchdowns %>
</p>

<p>
  <strong>Score penalties:</strong>
  <%= @puppy.score_penalties %>
</p>

<p>
  <strong>Score takeaways:</strong>
  <%= @puppy.score_takeaways %>
</p>

<p>
  <strong>Score tackles:</strong>
  <%= @puppy.score_tackles %>
</p>

<p>
  <strong>Puppy pic:</strong>
  <%= @puppy.pic %>
</p>

<%= link_to 'Edit', edit_puppy_path(@puppy) %> |
<%= link_to 'Back', puppies_path %>