config/routes.rb
Rails.application.routes.draw do

  root 'home#rankingslanding'
  get '/home' => 'home#index'
  get '/admin' => 'puppies#index'
  get '/admin/puppiesall' => 'puppies#puppiesall'
  get 'puppy/add' => 'puppies#add'
  get '/draft' => 'home#draft'
  get '/created' => 'home#created'
  get '/vote' => 'home#vote'
  post '/dovote' => 'home#dovote'
  get '/voted' => 'home#voted'
  get '/edit' => 'home#edit'
  get '/selfclose' => 'home#selfclose'
  get '/finalstats' => 'home#finalstats'
  post '/createteam' => 'home#createteam'
  post '/editteam' => 'home#editteam'
  get '/rankings' => 'home#rankings'

  resources :users, only: :index
  scope '/admin' do
  resources :teams
  resources :puppies
  resources :settings
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations",
                                       :sessions => "sessions" }

end

app/views/layouts/admin_panel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puppy Bowl Admin Panel</title>
  <%= stylesheet_link_tag    'admin_panel', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin_panel', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background:none;background-color:#f8f8f8; padding-top:0px;" data-no-turbolink>

  <div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">

      <div class="navbar-header">
       <!-- <img class="img-responsive" src="/assets/pbx_logo.png" alt="Pbx logo" style="height:50px; margin-left:20px; display:inline;"> -->
       <%= image_tag "pbx_logo.png", class: "img-responsive", style: "height:50px; margin-left:20px; display:inline;" %>
       <h2 style="display:inline; color:#1D6D19"> Puppy Bowl XI - Admin Panel </h2>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="/">Doctor Profile</a> -->
      </div>
      <!-- /.navbar-header -->

      <ul class="nav navbar-top-links navbar-right">
        <!-- /.dropdown -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
          <% if user_signed_in? %>
          <li><%= link_to '<i class="fa fa-sign-out fa-fw"></i> Sign out'.html_safe, destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li><%= link_to '<i class="fa fa-sign-out fa-fw"></i> Log in'.html_safe, new_user_session_path, :method => :get %></li>
          <% end %>
        </ul>
        <!-- /.dropdown-user -->
      </li>
      <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <% if current_user %>
          <% if user_signed_in? %>
          <li>
           <%= link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, puppies_path %>
          </li>
           <li>
           <%= link_to '<i class="fa fa-trophy fa-fw"></i> Puppies'.html_safe, '/admin/puppiesall' %>
          </li>
           <li>
            <%= link_to '<i class="fa fa-male fa-fw"></i> Teams'.html_safe, teams_path %>
          </li>
          <li>
            <%= link_to '<i class="fa fa-cog fa-fw"></i> Settings'.html_safe, settings_path %>
          </li>
          <% end %>
          <% end %>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>

  </nav>

</div>

<div id="page-wrapper">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= yield %>

</div>
<!-- /#page-wrapper -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puppy Bowl XI Fantasy Game</title>
  <meta name="description" content="Draft your Puppy Bowl XI Fantasy Team now and watch Animal Planet on Sunday, Feb. 1, at 3PM to see how your team fares on the grand gridiron of Puppy Bowl XI." />
  <!-- for Facebook -->
  <meta property="og:title" content="Puppy Bowl XI Fantasy Game" />
  <meta property="og:type" content="article" />
  <meta property="og:image" content="assets/main_screen.png" />
  <meta property="og:url" content="http://puppy-bowl.herokuapp.com/" />
  <meta property="og:description" content="Puppy Bowl XI is coming! Draft your dream team of pups NOW and then tune in Sunday, Feb. 1, at 3 PM E/P to see how your fantasy team fares." />
  <meta name="viewport" content="width=device-width">
  <link rel="shortcut icon" href="/favicon.ico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
  <% if user_signed_in? %>
<style type="text/css">
  
  .user-img-div { 
   width:44px;
   height:44px;
   background:url('<%= current_user.image_url.present? ? current_user.image_url : "/assets/missing.jpg" %>');
   background-repeat: no-repeat;
   background-size: 100% 100%;
  }
</style>
<% end %>
<body data-no-turbolink>
  <!--[if lt IE 10]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
<script type="text/javascript">
var CookieName = "TestCookie";
document.cookie = CookieName+"=yes;";
if(document.cookie.indexOf(CookieName) == -1) {
   console.log("Cookies are required but not enabled");
   }
else {
   console.log("Cookies ok.");
}   

        <% if user_signed_in? %>
    var userAgent = navigator.userAgent || navigator.vendor || window.opera;

  if( userAgent.match( /iPad/i ) || userAgent.match( /iPhone/i ) || userAgent.match( /iPod/i ) ) {
         var p = window.location.pathname; 
         console.log(p)
        if (p.indexOf('facebook/callback') > -1 ) { 
        /*  if(window.opener) {
          console.log('reloading with window opener...' + window.opener.location)
            window.opener.location.reload()
            window.blur()
            window.opener.focus()
            window.close()
          }
          else {*/
          console.log('reloading...')
         parent.location.reload()
    // }
        }
   }
        <% end %>
</script>



<div class="container">
  <% if flash[:notice] || flash[:error] %>
    <div class='notifications top-right'></div>
  <% end %>
  <div class="col-md-12 col-sm-12 col-xs-12 col-centered">
  <div class="row mb-20">
    <% if user_signed_in? %>
      <div class="col-md-1 col-sm-1 col-xs-2">
      <div class="user-img-div"> </div>
      </div>
      <div class="col-md-7 col-sm-7 col-xs-7">
        <p class="user-message">
          <span><%= current_user.first_name %></span>, pick your pups!
        </p>
        <%= link_to 'Signout'.html_safe, destroy_user_session_path, class: "btn signout", :method => :delete %>
      </div>
    <% end %>
    <div class="<%= user_signed_in? ? 'col-md-4 col-sm-4 col-xs-3' : 'col-md-12 col-sm-12 col-xs-12' %>">
      <div class="pull-right">
        <p class="sponsor pull-right">brought to you by</p>
        <%= link_to image_tag("logo-bravecto.png"), "http://www.mypet.com/bravecto.aspx?utm_source=MNINetwork%20&utm_medium=logo%20&utm_term=Fantasy%20Game%20&utm_content=logo&utm_campaign=2015%20BRAVECTO%20Campaign%20", class: "img-responsive", target: "_blank" %>
      </div>
    </div>
  </div>
<!--       <div class="row mb-65 hidden-xs"></div>
      <div class="row mb-30 visible-xs"></div> -->
    <%# end %>
    <div class="row">
      <div class="col-md-2 col-sm-2 col-xs-2 nopadding">
        <%= link_to (image_tag "pbx_logo.png", class: "img-responsive pull-right"), "/" %>
      </div>
      <div class="col-md-10 col-sm-10 col-xs-10 nopadding">
        <%= image_tag "fantasy-draft.png", class: "img-responsive center-block mb-15" %>
        <% unless user_signed_in? || current_page?(new_user_session_path) %>
            <div class="col-md-11 col-sm-11 col-xs-12 nopadding">
              <div class="welcome"><span>Welcome to the</span> PUPPY BOWL XI FANTASY DRAFT!</div>
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <p style="padding:0px;margin:0px;">
                    <a href="#" data-toggle="modal" data-target="#sign-up">
                      <%= image_tag "create_team_button.png", :'data-alt-src' => "assets/create_team_button_hover.png", class: "img-responsive", id: "create_team", style: "min-width:220px" %>
                    </a>
                  </p>
                  <p class="have-team">Already have a team? 
                  <a href="#" data-toggle="modal" data-target="#sign-in">EDIT YOUR PICKS
                  <i class="el-icon-chevron-right"></i>
                  </a>
                  </p>
                </div>
              </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-11 col-xs-11 col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
      <%= image_tag "landing_art_new.png", class: "img-responsive center-block" unless user_signed_in? || current_page?(new_user_session_path) %>
    </div>
  </div>
</div>
  <%= yield %>
<script>
  $('.top-right').notify({
    message: { text: '<%= flash[:notice] ? flash[:notice] : flash[:error] %>' }
  }).show(); // for the ones that aren't closable and don't fade out there is a .hide() function.
</script>
</body>
</html>

app/views/layouts/application_rankingslanding.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puppy Bowl XI Fantasy Game</title>
  <meta name="description" content="Draft your Puppy Bowl XI Fantasy Team now and watch Animal Planet on Sunday, Feb. 1, at 3PM to see how your team fares on the grand gridiron of Puppy Bowl XI." />
  <!-- for Facebook -->
  <meta property="og:title" content="Puppy Bowl XI Fantasy Game" />
  <meta property="og:type" content="article" />
  <meta property="og:image" content="assets/main_screen.png" />
  <meta property="og:url" content="http://puppy-bowl.herokuapp.com/" />
  <meta property="og:description" content="Puppy Bowl XI is coming! Draft your dream team of pups NOW and then tune in Sunday, Feb. 1, at 3 PM E/P to see how your fantasy team fares." />
  <meta name="viewport" content="width=device-width">
  <link rel="shortcut icon" href="/favicon.ico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
  <!--[if lt IE 10]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
<div class="container">
  <div class="col-md-12 col-sm-12 col-xs-12 col-centered">
  <div class="row mb-20">
    <div class="<%= user_signed_in? ? 'col-md-4 col-sm-4 col-xs-3' : 'col-md-12 col-sm-12 col-xs-12' %>">
      <div class="pull-right">
        <p class="sponsor pull-right">brought to you by</p>
        <%= link_to image_tag("logo-bravecto.png"), "http://www.mypet.com/bravecto.aspx?utm_source=MNINetwork%20&utm_medium=logo%20&utm_term=Fantasy%20Game%20&utm_content=logo&utm_campaign=2015%20BRAVECTO%20Campaign%20", class: "img-responsive", target: "_blank" %>
      </div>
    </div>
  </div>
<!--       <div class="row mb-65 hidden-xs"></div>
      <div class="row mb-30 visible-xs"></div> -->
    <%# end %>
    <div class="row">
      <div class="col-md-2 col-sm-2 col-xs-2 nopadding">
        <%= link_to (image_tag "pbx_logo.png", class: "img-responsive pull-right"), "/" %>
      </div>
      <div class="col-md-10 col-sm-10 col-xs-10 nopadding">
        <%= image_tag "fantasy-draft.png", class: "img-responsive center-block mb-15" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-11 col-xs-11 col-md-offset-1 col-sm-offset-1 col-xs-offset-1">     
    </div>
  </div>
</div>
  <%= yield %>
</body>
</html>

app/views/layouts/empty.html.erb
<%= yield %>